-- MySQL Script generated by MySQL Workbench
-- Fri Mar 31 15:56:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE stud_v23_tda072;
-- -----------------------------------------------------
-- Table `spørsmålskategori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spørsmålskategori` ;

CREATE TABLE IF NOT EXISTS `spørsmålskategori` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `navn` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `navn_UNIQUE` (`navn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin` ;

CREATE TABLE IF NOT EXISTS `admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(50) NOT NULL,
  `passord` VARCHAR(102) NOT NULL,
  `fornavn` VARCHAR(50) NULL,
  `etternavn` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spørsmål`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spørsmål` ;

CREATE TABLE IF NOT EXISTS `spørsmål` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `spørsmål` TEXT(500) NOT NULL,
  `kategori_id` INT UNSIGNED NOT NULL,
  `admin_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `spørsmål_kategori_id_idx` (`kategori_id` ASC) VISIBLE,
  INDEX `spørsmål_admin_id_idx` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `spørsmål_kategori_id`
    FOREIGN KEY (`kategori_id`)
    REFERENCES `spørsmålskategori` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `spørsmål_admin_id`
    FOREIGN KEY (`admin_id`)
    REFERENCES `admin` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svarmulighet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `svarmulighet` ;

CREATE TABLE IF NOT EXISTS `svarmulighet` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `svar` TEXT(500) NOT NULL,
  `korrekt` TINYINT NOT NULL,
  `spørsmål_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `svarmulighet_spørsmål_id_idx` (`spørsmål_id` ASC) VISIBLE,
  CONSTRAINT `svarmulighet_spørsmål_id`
    FOREIGN KEY (`spørsmål_id`)
    REFERENCES `spørsmål` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz` ;

CREATE TABLE IF NOT EXISTS `quiz` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `navn` VARCHAR(50) NOT NULL,
  `beskrivelse` TEXT(1000) NULL,
  `admin_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `quiz_admin_id_idx` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `quiz_admin_id`
    FOREIGN KEY (`admin_id`)
    REFERENCES `admin` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spørsmål_har_quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spørsmål_har_quiz` ;

CREATE TABLE IF NOT EXISTS `spørsmål_har_quiz` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `spørsmål_id` INT UNSIGNED NOT NULL,
  `quiz_id` INT UNSIGNED NOT NULL,
  INDEX `shq_quiz_id_idx` (`quiz_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `shq_spørsmål_id`
    FOREIGN KEY (`spørsmål_id`)
    REFERENCES `spørsmål` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `shq_quiz_id`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `quiz` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_sesjon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_sesjon` ;

CREATE TABLE IF NOT EXISTS `quiz_sesjon` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `spørsmål_har_quiz_id` INT UNSIGNED NOT NULL,
  `svar_id` INT UNSIGNED NULL,
  `dato_tid` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `sesjon_svarmulighet_id_idx` (`svar_id` ASC) VISIBLE,
  INDEX `sesjon_shq_id_idx` (`spørsmål_har_quiz_id` ASC) VISIBLE,
  CONSTRAINT `sesjon_svarmulighet_id`
    FOREIGN KEY (`svar_id`)
    REFERENCES `svarmulighet` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `sesjon_shq_id`
    FOREIGN KEY (`spørsmål_har_quiz_id`)
    REFERENCES `spørsmål_har_quiz` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
